# Generated by Django 5.2.17 on 2026-08-11 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seguir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seguido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguidores_rel', to=settings.AUTH_USER_MODEL)),
                ('seguidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguindo_rel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'seguir',
                'indexes': [models.Index(fields=['seguido'], name='ix_seguir_seguido_id')],
                'constraints': [models.UniqueConstraint(fields=('seguidor', 'seguido'), name='seguir_seguidor_seguido_uniq')],
            },
        ),
    ]
