"""Limites do contrato da API — evita números mágicos espalhados."""

POST_MAX_LENGTH = 280
NOME_MAX_LENGTH = 100
EMAIL_MAX_LENGTH = 100
SENHA_MIN_LENGTH = 6
SENHA_MAX_LENGTH = 72

FOTO_MAX_BYTES_DEFAULT = 5 * 1024 * 1024
FOTO_CHUNK_SIZE = 64 * 1024

LIST_LIMIT_DEFAULT = 50
LIST_LIMIT_MIN = 1
LIST_LIMIT_MAX = 200
LIST_OFFSET_MIN = 0

SEARCH_LIMIT_DEFAULT = 20
SEARCH_LIMIT_MIN = 1
SEARCH_LIMIT_MAX = 50
POSTS_PER_USER_DEFAULT = 5
POSTS_PER_USER_MIN = 0
POSTS_PER_USER_MAX = 20

LIKE_BATCH_MIN = 1
LIKE_BATCH_MAX = 100

ACCESS_TOKEN_EXPIRE_MINUTES_DEFAULT = 120

JWT_ALGORITHM = "HS256"

CLOUDINARY_FOLDER = "rocketmail/avatars"
MEDIA_AVATARS_PREFIX = "/media/avatars"
