# Generated by Django 5.2.17 on 2026-08-11 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=280)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'post',
                'indexes': [models.Index(fields=['usuario'], name='ix_post_usuario_id'), models.Index(fields=['-data_criacao'], name='ix_post_data_criacao')],
            },
        ),
    ]
